language: python

env:
  - TOXENV=flake8
  - TOXENV=py26-Django-1.6.x
  - TOXENV=py26-Django-1.7.x
  - TOXENV=py27-Django-1.6.x
  - TOXENV=py27-Django-1.7.x
  - TOXENV=py32-Django-1.6.x
  - TOXENV=py32-Django-1.7.x
  - TOXENV=py33-Django-1.6.x
  - TOXENV=py33-Django-1.7.x
  - TOXENV=py34-Django-1.6.x
  - TOXENV=py34-Django-1.7.x

install:
  - pip install coveralls
  - pip install tox

script:
  - tox

after_success:
  - coverage combine
  - coveralls
